steps:
  - id: "submit dataflow job"
    name:  'docker.io/library/python:3.8'
    entrypoint: bash
    args: 
      - '-c'
      - | 
        dataflow
        
options:
  logging: CLOUD_LOGGING_ONLY
