steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirement.txt", "--user"]
    
  - name: python
    entrypoint: python
    args: [
      '-m','test',
      '--runner', 'DataFlowRunner',
      '--project', 'named-inn-349004',
      '--temp_location', 'gs://named-inn-349004/temp',
      '--region','us-central1',
      '--job_name', 'test']
options:
  logging: CLOUD_LOGGING_ONLY
