steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://github.com/phanigeth42/demo.git', 'repo_dir']
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: bash
    args:
      - '-c'
      - |
        repo_dir/java/submit.sh -Dexec.args="--project=named-inn-349004 --region=us-central1 --inputTopic=projects/named-inn-349004/topics/test --output=gs://named-inn-349004/samples/output --gcpTempLocation=gs://named-inn-349004/temp --runner=DataflowRunner --windowSize=2 --jobName=test3"
options:
  logging: CLOUD_LOGGING_ONLY
