steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://github.com/phanigeeth42/demo.git', 'repo_dir']
  - id: "submit dataflow job"
    name:  maven:3.6.3-jdk-8
    entrypoint: bash
    args: 
      - '-c'
      - | 
        bash submit.sh
    dir: 'repo_dir/java'
        
options:
  logging: CLOUD_LOGGING_ONLY
timeout: 120s
